### ISSUE TITLE
2.0.0 Tracking Issue

### ISSUE THREAD

**Issue by Pyrbu** [Pyrbu/ZNPCsPlus#38]
This is the tracking issue for the 2.0.0 release of the plugin, if you think you are able to and are willing to complete/help with any of the uncompleted tasks below please contact me in our [plugin discord](https://discord.gg/MAZz6XpPcg) and I will point you in the right direction

- [x] Rewrite entity system transitioning from reflection to packets
- [x] Rewrite holograms
- [x] Rewrite interactions system
- [x] Rewrite NPC registry
- [x] Rewrite skin system (make it more reliable) 
- [x] Add Folia support 
- [x] Rewrite commands
- [ ] Add new storage system that supports different storage types (MongoDB, MariaDB, YAML)
- [x] Add converter for legacy data (old ZNPCs)
- [x] Add API for plugin developers

**Comment by PikaMug** [comment]
I would be interested in helping rewrite commands. For example, `/znpcs create <id> <type> <name>` has a lot of issues, like it shouldn't be necessary to specify an ID, and type should be optional (provided PLAYER is default). In fact, misspelling the type generates a pretty unfriendly CommandExecuteException, and having too few arguments just replies "Incorrect use of command." without any suggestions. Lastly, tab completion should be a priority.

As for storage, you might be interested in the model I've adapted at <https://github.com/PikaMug/Quests/tree/main/core/src/main/java/me/blackvein/quests/storage> or lucko's [helper](https://github.com/lucko/helper) library

**Comment by Aitooor** [comment]
**Server version:**
This server is running Folia version git-Folia-"d34fb87" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: d34fb87)
You are 14 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Folia-"32417a2" (MC: 1.19.4)

**Issue:**
Teleport issue(You need to use "Entity#teleportAsync()": https://paste.md-5.net/edubiyibep.bash
Commands feed back not working(only in the final command. Example /znpcs) The commando not show nothing in Folia

**Comment by Aitooor** [comment]
**Feature add request**
I think you need to add support to ItemsAdder/MythicMobs/ModelEngine for CustomModelData mobs hook. Just like Citizens2 does

**Comment by Pyrbu** [comment]
Closing because this is stale, if you want to stay up-to-date with the development of 2.0.0 please join the discord
